# Credentials copied from apps/default/postgresql/manifests/n8n-db.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    argocd.argoproj.io/sync-wave: "-1"
  creationTimestamp: null
  name: n8n-postgres-credentials
spec:
  encryptedData:
    password: AgBShiHPCTcTUYIqWnNRB7yoKJqkMjG8HptDkhiw3xkBNEtc8JfJyKV77l8rUr8yDcrgAjvQVxSvD5tMn3vaMHUgGaQVMd5Gc248vinIjt/DtpJeRIqEm7yIQ9Xi0WstgrgXp0wDkpeHpD6i1RIClEpy44HSkU79mi08j9Kc+/j8gax9dRld7AT/P7Y8GJm6ySYWzQgMil6Pz8frkWUcnL+NZFul7lIsB3wfCYAm6wNa3FOFgYx6UII1E+KpteiTycAfSwcn/T7DDmUu2mTOP3tMY/iTANdEvNs+ryiZ5u9zTzPvAvYi7evvIRV7TBiVItEJ+5G2vRULVslFHuLYw6YZPZk8iLCF3bFQB6Z+ni2LBFrLTsXLQFEEjWOF6ZEI5QMz1f4J8KbraolexfbfzYcKGu4bwH4nm5K9QiOfrw8zsF2GT+TFzn9Ka7JtMDk5ZtFsg6Xvi9F7Gt4v7kdRv+h9HSck7Tmx7baJO/jSY4AFM3OAh69jSRh/iGCOKI6AUrpJ2MXNDMdpj0wEdB25G5EJpxghp+J/49Y05J1LnVlW8RLcYFWCr40IdX165EMQf3TELDM5zQFcMgHNh93j+7silje+NCRcKJn5EtHZMDfdrFfZDuAA0s9oL2vgGTnrpbYrISggXtMszCc+zWevJc9pPi6uKHrrfYVUaPpp5Nq+/tNi1c5mAEmCsR1GKYowhBY4dyCrV4FCDXdPbLGV3C8RNnKz9iB9eA91
    username: AgCMTRp7pROFZUeU5ltM+RG3DuSQIZIKP86zRkwh9ql/FIn3B0blRJEFYGdvxluBqfpJ8F4Mm/TcNq6atK5E6GtJeaf/S8QZ4oM5IjV3v8rpBrJ1iwUt1szPbUSJs2UQho2l9WX6HZoVea7rHNlj/q7rtZT70/HYIjQbB6hdGsecGkEMxdjwgqftvQHR8ai3F9ZKbDkXJXx3/t25GGcbIbstn6kFz9Ussu9IMclRoV4wVVYvZ50/OEuwMr+940DdXseVam2A5d1XYuqQFSThp38p1HBPSeEMm+qA5Coqb6IRVX6odbyPmrK30ocR7t2xGUGiwAgiMqiyQPDdGVaXZSJwMifoH4BBvhTzKqVkzMd0K2n39MuSk9UgRPHK880SmWiTJ4HqB9ETq5hUE+zGs5W0EqPCkDmss+lzyuxCjuotneZoo6ZxvKs9pobau7vYTyr/R6WNhzTWcCKLk9Kbt3PriBOIwkrwhlRZ26y00bKjlGq5VsPZ2OE+NrXSbtFuZC7456ubd4HafxhcAhzOkG5RKxC2JJ5GZ6RW8fVCpAvDNwxNyB4fpho4emPbni/3ADfbdf1mOmoaecmHTc1R9LMe07AHdXLNNwLPutmXYykhaz2nTnlKQRNXdqjGMDxbMJgJfFflxLlJ68En95TTuzrXj+wqNHunwYQcilLdbsQ2+45sNYRX9F4KjTh7lOifPUcMCuk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        argocd.argoproj.io/sync-wave: "-1"
      creationTimestamp: null
      name: n8n-postgres-credentials
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: n8n-postgres-admin-credentials
spec:
  encryptedData:
    password: AgBrfp+SbLgt9TrW5g90OJuXcqdE7EpObxzHbXTB4IFGMeiuKbCjQSL+Nb0vr2p9Rb9HbBuU9WzNBB+mEMA60zmVyGlr57ZdHQsO+JWqnBbpCNPJMRCWHXRLzTusdRFsMjX6yvH5AperkGuf8BzMqWT4X7fGuf1cni+qX6tW2eXodU7RYoND3iTC1L7Bj3q+FTFFJkVvtQ2ltD9SUMHgetPY7jyOArY+Z40Pa3QOHIxRFK+kvXzMBtQkQ11QBgbJ+l0azGAIcUjvVDAj1R6If69GAwe5y3ibrdZDuF4Do5jXXtv/d2mNgOH3kzUdsaacOlhj7pt3K92U2fVESJjqfpi4r3YKVopycArRmRh5coJJbqyW2zxBqjJHZ5YfEessYOUjxrF+8+uRvoNKkxGCOFzvp5KG/z90InxafSHaOMX/ba4VMa4WwF2QdKp7JFfM/YXSCc8ItLbNJYGmyn3a5b4hPxLNFwaP1cAZMMfSrIIXGJJJ6KtztS9qXkEGep4ZHrEFkG6M+0h8ekAvR6krcggqoQ8MOIZIAoSFGwAwqHuudvEJYDkW4m2w7mriH9oKwEwtirVP8B2NZyHnQWLd5/ZJVxlgFsBnuBx1eAq/qMX9AzSHhBHaIwturAQIRh1mvSoECb10/QQuCiw2iGxcH1g5MTFBEUJwlSnRZYAv+AwefoRaYDkvc2jivf8QljneD+rGkmzvqkRk2sqGmf6TSmVCvxqdHShYoZ76
    username: AgCFU+ILFU6jat3gpyEwMl+LEjkYdL0PJBt0ofQtsX195xlNOcAGCfhcFJQ4LpCzudc70XM7erf7WnK3p9JBlDN78Ae8e5MgjtcmkSdwCU98rEWuezgm1BwMyX0XqFnpQQ20jls4btw8I5rWBzGYosPRmy75pHl2281+OmYqoysKluijV5Kl3dVKNnF3NprdkC9goxRkTntIU50L5VOw7s3ST/Vn7GmfJbnjAFBtJ4iXcVE3diaHJXpLnYvESXyFH9LgaJ2Nru1UoHJWPfaYdO1Wih96nhj/TAdRfbJ4YdfTSuGbK+MCQ3f2OBw4ffZRdDR/SQRLCi/Fw4R4BASVbF0AvewsapMuz7eXQJNbVarv983gL3toslADX/2Wxo7E1Lg28Avgjo568/j2SkK8d3/skVmg72CQdBfVto7R98f8efob5kXG8aUNljPKMp90o0OCtFNake0yRkCct9NTc66+mZc2+2zXEyhdTXc8JqPh4g+iO/HbW4gD367oPN6RDGig1C4EItrrvLYtTcl1mYxDH17Z12vcd7Jdw8CQxOUO5gKUOjUAw1hiRL9IqBdw3B63D17qjrZIlOfElAtBM258UzeZ5nipJuBPYwkO56IWAj/n9JcQ8Pd1k+iVhm/h06rBEARqcYv3lmwYKVEdLJuCewNWlsywktIZSwpEkmr5tndr62DSEEEJyvwD8XurnEoguzjTwcFhCQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: n8n-postgres-admin-credentials
    type: kubernetes.io/basic-auth
---
