apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Workflow automation platform
    gethomepage.dev/group: AI
    gethomepage.dev/icon: n8n
    gethomepage.dev/name: n8n
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    - host: n8n.$(DNS)
      http:
        paths:
          - backend:
              service:
                name: n8n-webhook
                port:
                  number: 5678
            path: /webhook/
            pathType: Prefix
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /webhook-test/
            pathType: Prefix
          - backend:
              service:
                name: n8n-webhook
                port:
                  number: 5678
            path: /form/
            pathType: Prefix
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /form-test/
            pathType: Prefix
          - backend:
              service:
                name: n8n-mcp-webhook
                port:
                  number: 5678
            path: /mcp/
            pathType: Prefix
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /mcp-test/
            pathType: Prefix
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /rest/oauth2-credential/callback
            pathType: Prefix
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /static/
            pathType: Prefix
          - backend:
              service:
                name: n8n-webhook
                port:
                  number: 5678
            path: /webhook-waiting/
            pathType: Prefix
          - backend:
              service:
                name: n8n-webhook
                port:
                  number: 5678
            path: /form-waiting/
            pathType: Prefix
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /
            pathType: Prefix