apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Workflow automation platform
    gethomepage.dev/group: Automation
    gethomepage.dev/icon: n8n
    gethomepage.dev/name: n8n
spec:
  rules:
    # DNS will be replaced by kustomize
    - host: n8n.$(DNS)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
