---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: n8n-postgres-credentials
spec:
  encryptedData:
    postgres-password: AgAmg/MhuJc49J4fxI2nFV52iEjUPT5XFTQWVpNfAXJn64mAven5bvPmw92nQMAfaoMjHFrrrXihAN9Nm6GFu4raCv5OUgaEqfEGAkiBFXTOoMC3sn1JxRywsXV9X5Orv+PdTyLmQAc9omoBXiEp5m0zJu3a2XBOOpGw89Hx531PufCjLhWPjfeLOj2soLDZHLLa8ForN51NOtZ8A2daz93fpEhmgiuFoUIz3sdp1EpyXdu9sxyML2QeQKYwXls7vxm+fxVy/JWKv9nqQrikxrvHouQBRPE5Mqw7hXZPu5Il93Hu13z6uD8AzqzZTod/e9qcYTrY9d/3VUukxFfQJY6YC7xIduk0fjS1/FSEPSXd6t3wXOdlOIeft9JO8ik+GNhT9USRG0BXGTOFMPdGbn6gOZWxU9z1tYkUgMRR6XJj80IXOrQMPbA4loNI9nmUuM3XHONkbOuxb/oqboeYq8gyylyN4SOMCc8HjNFv2dxikeqrd66jeHcaA0YK3rjjWpyTkdt9mxIX2q8QMWUPlQ4jIVDBiilws0TCWflkQzCyfJkbxYnoyXsG0l+Vm3FNoOQ/1MEqVTouH8j2F3bq6FcubmgkGznzcSHyTVnQnFK9Q+SdFokQRFkF8751i+sLJmiipn6XHsGGkQPHY/G76NOWP7/hlD0oW2whQHdf6v6lLSKTa/5r51Bc5BzPUPSyI7vafW4IL3tcESZHOJKlcSu1hRHvfxcww18v
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: n8n-postgres-credentials
    type: Opaque
