apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: n8n-tunnel-binding
subjects:
  - name: n8n # name of service
  - name: n8n-webhook # name of webhook service
tunnelRef:
  kind: ClusterTunnel
  name: homelab-cluster-tunnel
