apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Ollama
    gethomepage.dev/description: Local LLM API
    gethomepage.dev/group: AI
    gethomepage.dev/icon: ollama
spec:
  rules:
    - host: ollama.$(DNS)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama
                port:
                  name: http
