apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: anne-cat-tunnel-binding
subjects:
  - name: whichcatisanne
  # add more services here if needed (e.g., webhook)
tunnelRef:
  kind: ClusterTunnel
  name: homelab-cluster-tunnel
