apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

resources:
  - manifests/ingress.yaml
  - manifests/postgres-credentials.yaml
  - manifests/n8n-encryption-key.yaml
  - manifests/tunnel-binding.yaml

helmCharts:
  - name: n8n
    repo: https://community-charts.github.io/helm-charts
    namespace: n8n
    releaseName: n8n
    version: 1.16.4
    valuesFile: values.yaml

replacements:
  - source:
      kind: Ingress
      name: n8n
      fieldPath: metadata.annotations.external_dns
    targets:
      - select:
          kind: Ingress
          name: n8n
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "n8n." prefix
          delimiter: "."
          index: 1
